### ISSUE TITLE
Compile for x64?

### ISSUE THREAD

**Issue by p1r473** [dananjayavr/HardwareMonitor#1]
Can you please Compile for x64? @dananjayavr

**Comment by dananjayavr** [comment]
I’m not sure I understand the question, would you like an executable for x64 or instructions for how to compile ?

**Comment by p1r473** [comment]
@dananjayavr just the executable please

**Comment by dananjayavr** [comment]
@p1r473 I have generated an executable for x64. It is available under Releases -> v0.0.1 -> Assets
Make sure to download the .exe and the .dll both!
